### ISSUE TITLE
design and implement a new JDF model

### ISSUE THREAD

**Issue by thiagomanel** [fogbow/arrebol#11]
We borrowed code from OurGrid. We need to decide with clauses and commands(?) and variables we need to support. For example, do we need put, store and playpen?  How about job labels?

Also, should we expose more oCCI to JDF? For example, should we allow to request a storage volume or a specific image?

**Comment by thiagomanel** [comment]
See below the spec of of the job description language. Some part of the spec are already implemented. Other parts need to be modified (e.g nowadays, it is possible to declare init, remote and final clauses in a task).

## JDL Spec

### Job

A job clause may contain four different sub-clauses, all of them are optional:
- [ ] label clause, which is used to provide a short description for the job;
- [ ] job requirements clause, which is used to define the requirements for the VM that needs to be used to run the tasks of the job;
- [ ] job init clause, which defines commands that should be executed before the start of every task;
- [ ] job final clause, which defines commands that need to be executed after the completion of every task.

### Task

The task clause is used to define each task of a job. The number of task clauses in the jdf determines the number of tasks in the job. A task in a BoT application is a sequence of commands that are executed one after the other, similar to the init and final sub-clauses of the job clause

## Example

```
job:
    label: my-simulation
    requirements: Glue2RAM >= 1024 AND Glue2CPU == 4
    init:
        put /home/fubica/common-in /tmp/common-in
    put /home/fubica/bin/my-simulator /tmp/my-simulator
    cd /tmp
    final:
        rm /tmp/intermediate* /tmp/in-scenario*
task:
    put /home/fubica/in-scenario1 /tmp/in-scenario1
    my-simulator common-in in-scenario1 > out-scenario1
    get /tmp/out-scenario1 /home/fubica/out-scneario1
task:
    put /home/fubica/in-scenario2 /tmp/in-scenario2
    my-simulator common-in in-scenario2 > out-scenario2
    get /tmp/out-scenario2 /home/fubica/out-scneario2
…
task:
    put /home/fubica/in-scenario1000 /tmp/in-scenario1000
    my-simulator common-in in-scenario1000 > out-scenario1000
    get /tmp/out-scenario1000 /home/fubica/out-scneario1000
```

**Comment by thiagomanel** [comment]
Note that, as fubica have said, if we have job labels in JDL, there is no need for friendly names in the CLI
